package com.crafteam.kata.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * Entity representing a client in the system.
 * 
 * This class maps to the "client" table in the database and stores
 * basic information about customers who place orders.
 */
@Getter
@Setter
@Entity
@ToString
public class Client {
    /**
     * Unique identifier for the client.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Client's first name.
     */
    private String firstName;

    /**
     * Client's last name.
     */
    private String lastName;

    /**
     * Client's delivery address.
     */
    private String address;
}
