package com.crafteam.kata.model;

import com.crafteam.kata.enums.DeliveryType;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Entity representing an order in the system.
 * 
 * This class maps to the "orders" table in the database and stores
 * information about customer orders including delivery details,
 * products, and order status.
 */
@Getter
@Setter
@ToString
@Entity
@Table(name = "orders")
public class Order {
    /**
     * Unique identifier for the order.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    /**
     * List of products included in this order.
     * Represents a many-to-many relationship with the Product entity.
     */
    @ManyToMany
    @JoinTable(
            name = "order_product",
            joinColumns = @JoinColumn(name = "order_id"),
            inverseJoinColumns = @JoinColumn(name = "product_id")
    )
    private List<Product> products;

    /**
     * Type of delivery requested for this order.
     * Can be DRIVE, DELIVERY, DELIVERY_TODAY, or DELIVERY_ASAP.
     * This field is required.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private DeliveryType deliveryType;

    /**
     * The client who placed this order.
     * Represents a many-to-one relationship with the Client entity.
     * This field is required.
     */
    @ManyToOne
    @JoinColumn(name = "client_id", nullable = false)
    private Client client;

    /**
     * Timestamp when the order was placed.
     * This field is required.
     */
    @Column(nullable = false)
    private LocalDateTime orderAt;

    /**
     * Start time of the delivery window.
     * Used for scheduled deliveries.
     */
    private LocalDateTime dateBeginOrder;

    /**
     * End time of the delivery window.
     * Used for scheduled deliveries.
     */
    private LocalDateTime dateEndOrder;

    /**
     * Current status of the order (e.g., PENDING, DELIVERED).
     * Note: Should be an enum for type safety.
     */
    private String status;

    /**
     * Expected delivery date for the order.
     */
    private LocalDateTime deliveryDate;
    
    /**
     * Selected time slot for delivery (e.g., "09:00-10:00").
     */
    private String timeSlot;
    
    /**
     * Indicates whether a delivery slot has been reserved for this order.
     */
    private boolean isReserved;
}
