package com.crafteam.kata.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * Entity representing a product in the system.
 * 
 * This class maps to the "products" table in the database and stores
 * information about items that can be ordered.
 */
@Getter
@Setter
@ToString
@Entity
@Table(name = "products")
public class Product {
    /**
     * Unique identifier for the product.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Product name/label.
     * This field is required and cannot be null.
     */
    @Column(nullable = false)
    private String label;
}
